# Generated by Django 5.0.6 on 2024-06-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=6)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                ("aadhar_number", models.CharField(max_length=12)),
                ("contact_number", models.CharField(max_length=10)),
                ("area_ploughed", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("Summer", "Summer"),
                            ("Winter", "Winter"),
                            ("Monsoon", "Monsoon"),
                        ],
                        max_length=10,
                    ),
                ),
                ("crops_grown", models.TextField()),
                (
                    "seeds_used",
                    models.CharField(
                        choices=[("Own", "Own"), ("Given by IFTR", "Given by IFTR")],
                        max_length=15,
                    ),
                ),
                ("date_of_seed_sown", models.DateField()),
                (
                    "transplanting",
                    models.CharField(
                        choices=[("Manual", "Manual"), ("Machine", "Machine")],
                        max_length=10,
                    ),
                ),
                (
                    "irrigation_method",
                    models.CharField(
                        choices=[
                            ("Borewell", "Borewell"),
                            ("Well", "Well"),
                            ("River", "River"),
                            ("Drip Irrigation", "Drip Irrigation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fertilisers_used",
                    models.CharField(
                        choices=[
                            ("Organic", "Organic"),
                            ("Chemical", "Chemical"),
                            ("Bio-inputs", "Bio-inputs"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_harvesting", models.DateField()),
                ("yield_in_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "financial_need",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=3
                    ),
                ),
            ],
        ),
    ]
