# Generated by Django 5.0.6 on 2024-06-22 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="farmer",
            table="form_table",
        ),
    ]
